baseURL = 'https://mikekasprzak.com/'
languageCode = 'en-us'
title = 'Mike Kasprzak'

[taxonomies]
#category = 'categories'
technology = 'technologies'
role = 'roles'
platform = 'platforms'

location = 'location'
